version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: mysql
    hostname: mysql
    networks:
      - net-backend
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - db.env

  streama:
    image: streama
    build: 
      context: .
      dockerfile: service.Dockerfile
    restart: always
    container_name: streama
    hostname: streama
    depends_on:
      - mysql
    networks:
      - net-backend
    expose:
      - 8080
    volumes:
      - ./videos:/data/streama # Change to your video folder
      - app_data:/app/streama
    env_file:
      - service.env

  proxy-reverse:
    image: nginx:alpine
    restart: always
    container_name: proxy-reverse
    hostname: proxy-reverse
    depends_on:
      - streama
    networks:
      - net-backend
    ports:
      - "80:80"
    volumes:
      - nginx.conf:/etc/nginx/conf.d/default.conf
      - proxy_reverse_data_log:/var/log/nginx

networks:
  net-backend:

volumes:
  db_data:
  app_data:
  proxy_reverse_data:
  proxy_reverse_data_log: